# Generated by Django 6.0.4 on 2026-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_society_contact_email_address_society_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/society/'),
        ),
    ]
